// File generated by FlutterFire CLI for the Catspot DEV environment.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for the Catspot **dev** Firebase project.
///
/// Use this file with `--flavor dev` or when `ENV=dev`.
class DefaultFirebaseOptionsDev {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'Dev FirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      default:
        throw UnsupportedError(
          'Dev FirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBignjJNFbYxBdp5mQ90LqHboAy8t_tM_E',
    appId: '1:805242372266:android:dca863304b48e714acd0d3',
    messagingSenderId: '805242372266',
    projectId: 'catspot-dev-2026',
    storageBucket: 'catspot-dev-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATNp9v_cVtHOLlVMAiiS24EDy7J5WQrtw',
    appId: '1:805242372266:ios:e1fc562589b7d1f4acd0d3',
    messagingSenderId: '805242372266',
    projectId: 'catspot-dev-2026',
    storageBucket: 'catspot-dev-2026.firebasestorage.app',
    iosBundleId: 'app.catspot.mobile',
  );
}
